export const VALID_PROMPT_BUILDER_MODELS = new Set(["gpt-5.5", "gpt-5.4", "gpt-5.4-mini"]);
export const DEFAULT_PROMPT_BUILDER_MODEL = "gpt-5.5";
export const MAX_MESSAGES = 24;
export const MAX_MESSAGE_CHARS = 16_000;
export const MAX_ATTACHMENTS = 6;
export const MAX_TEXT_ATTACHMENT_CHARS = 20_000;
export const MAX_ATTACHMENT_NAME_CHARS = 160;
export const MAX_ATTACHMENT_MIME_CHARS = 120;
export const PROMPT_BUILDER_RESPONSE_MAX_OUTPUT_TOKENS = 2400;
