import { registerCapabilitiesRoutes } from "./capabilities.js";
import { registerEventsRoute } from "./events.js";
import { registerHealthRoutes } from "./health.js";
import { registerHistoryRoutes } from "./history.js";
import { registerAssetsRoutes } from "./assets.js";
import { registerSessionRoutes } from "./sessions.js";
import { registerEditRoutes } from "./edit.js";
import { registerNodeRoutes } from "./nodes.js";
import { registerGenerateRoutes } from "./generate.js";
import { registerMultimodeRoutes } from "./multimode.js";
import { registerStorageRoutes } from "./storage.js";
import { registerCardNewsRoutes } from "./cardNews.js";
import { registerMetadataRoutes } from "./metadata.js";
import { registerPromptRoutes } from "./prompts.js";
import { registerPromptImportRoutes } from "./promptImport.js";
import { registerAnnotationRoutes } from "./annotations.js";
import { registerCanvasVersionRoutes } from "./canvasVersions.js";
import { registerComfyRoutes } from "./comfy.js";
import { registerImageImportRoutes } from "./imageImport.js";
import { registerPromptBuilderRoutes } from "./promptBuilder.js";
import { registerAgentRoutes } from "./agent.js";
import { registerGrokRoutes } from "./grok.js";
import { registerAgyRoutes } from "./agy.js";
import { registerVideoRoutes } from "./video.js";
import { registerVideoExtendedRoutes } from "./videoExtended.js";
import { registerQuotaRoutes } from "./quota.js";
import { registerAuthRoutes } from "./auth.js";
import { mountKeyRoutes } from "./keys.js";
import { registerGenerationRequestLogRoutes } from "./generationRequestLog.js";
import { requireRuntimeContext } from "../lib/runtimeContext.js";
export function configureRoutes(app, ctxRaw) {
    const ctx = requireRuntimeContext(ctxRaw);
    registerEventsRoute(app, ctx);
    registerHealthRoutes(app, ctx);
    registerCapabilitiesRoutes(app, ctx);
    registerStorageRoutes(app, ctx);
    registerMetadataRoutes(app, ctx);
    registerHistoryRoutes(app, ctx);
    registerAssetsRoutes(app, ctx);
    registerAnnotationRoutes(app, ctx);
    registerCanvasVersionRoutes(app, ctx);
    registerImageImportRoutes(app, ctx);
    registerComfyRoutes(app, ctx);
    registerSessionRoutes(app, ctx);
    registerEditRoutes(app, ctx);
    registerNodeRoutes(app, ctx);
    if (ctx.config.features.cardNews)
        registerCardNewsRoutes(app, ctx);
    registerMultimodeRoutes(app, ctx);
    registerGenerateRoutes(app, ctx);
    registerAgentRoutes(app, ctx);
    registerPromptBuilderRoutes(app, ctx);
    registerPromptRoutes(app, ctx);
    registerPromptImportRoutes(app, ctx);
    registerGrokRoutes(app, ctx);
    registerAgyRoutes(app);
    registerVideoRoutes(app, ctx);
    registerVideoExtendedRoutes(app, ctx);
    registerQuotaRoutes(app, ctx);
    registerAuthRoutes(app);
    mountKeyRoutes(app, ctx);
    registerGenerationRequestLogRoutes(app, ctx);
}
